---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: component-upgrade-logger-pipeline-trigger
  labels:
    paas.redhat.com/appcode: SET-001
spec:
  schedule: "0 6 * * 1" # Monday morning
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 10
  backoffLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-cron-runner
          containers:
            - name: tkn
              image: gcr.io/tekton-releases/dogfooding/tkn
              # modify the pipeline name bellow if needed
              # (component-upgrades-logger-native-pipeline or component-upgrades-logger-jvm-pipeline)
              command: [ "tkn", "pipeline", "start", "component-upgrades-logger-native-pipeline",
                         "--serviceaccount=build-bot",
                         "-w", "name=shared-workspace,claimName=build-volume,subPath=component-upgrade-logger",
                         "-w", "name=maven-settings,emptyDir=",
                         "-w", "name=kubeconfig-workspace,emptyDir=",
                         "--use-param-defaults"]
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 50m
                  memory: 20Mi
          restartPolicy: Never
