apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: component-upgrades-logger-native-pipeline
  labels:
    paas.redhat.com/appcode: SET-001
spec:
  params:
    - name: gitUrl
      type: string
      description: The git repository URL to clone from.
      default: https://github.com/TomasHofman/component-upgrade-logger
    - name: gitRevision
      type: string
      description: The git branch to clone.
      default: main
    - name: contextDir
      description: The context directory from where to build the application
      default: .
    - name: baseImage
      description: Base runner image
      default: registry.access.redhat.com/ubi8/ubi-minimal
#    - name: targetImage
#      description: Name of the runner image to build
#      default: images.paas.redhat.com/thofman/component-upgrade-logger:native-1.0.0-SNAPSHOT
#    - name: dockerfile
#      description: Path to the dockerfile in the source code
#      default: src/main/docker/Dockerfile.native
    - name: registrySecretName
      description: Name of the secret with container registry credentials to push the image.
      default: images-paas-redhat-com-thofman
  workspaces:
    - name: shared-workspace
    - name: maven-settings
    - name: kubeconfig-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
        - name: deleteExisting
          value: "true"
    - name: build-push-image
      taskRef:
        name: maven-quarkus
      runAfter:
        - fetch-repository
      params:
        - name: CONTEXT_DIR
          value: $(params.contextDir)
        - name: REGISTRY_SECRET_NAME
          value: $(params.registrySecretName)
        - name: GOALS
          value:
            - -DskipTests=true
            - -Dmaven.javadoc.skip=true
            - -Dmaven.site.skip=true
            - -Dmaven.source.skip=true
            - -Djacoco.skip=true
            - -Dcheckstyle.skip=true
            - -Dfindbugs.skip=true
            - -Dpmd.skip=true
            - -Dfabric8.skip=true
            - -e
            - -B
            - -Pnative
            - -Dquarkus.container-image.build=true
            - -Dquarkus.container-image.push=true
            - -Dquarkus.native.native-image-xmx=5g
            - package
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
#    - name: build-image
#      taskRef:
#        name: my-buildah
#      runAfter:
#        - build-app
#      params:
#        - name: IMAGE
#          value: $(params.targetImage)
#        - name: DOCKERFILE
#          value: $(params.dockerfile)
#      workspaces:
#        - name: source
#          workspace: shared-workspace
    - name: rollout
      taskRef:
        name: kubernetes-actions
      runAfter:
        - build-push-image
      params:
        - name: args
          value:
            - rollout
            - restart
            - deployment/component-upgrade-logger
      workspaces:
        - name: manifest-dir
          workspace: shared-workspace
        - name: kubeconfig-dir
          workspace: kubeconfig-workspace