apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-volume
  labels:
    paas.redhat.com/appcode: SET-001
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: dynamic-nfs
  volumeMode: Filesystem