apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-volume
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: dynamic-nfs
  volumeMode: Filesystem