---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cron-runner
  labels:
    paas.redhat.com/appcode: SET-002
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "pipelineruns", "pipelineresources"]
    verbs: ["get", "list", "delete", "patch", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-rollouts
  labels:
    paas.redhat.com/appcode: SET-002
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "patch", "create" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cron-runner
  labels:
    paas.redhat.com/appcode: SET-002
subjects:
  - kind: ServiceAccount
    name: sa-cron-runner
roleRef:
  kind: Role
  name: cron-runner

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-bot
  labels:
    paas.redhat.com/appcode: SET-002
subjects:
  - kind: ServiceAccount
    name: build-bot
roleRef:
  kind: Role
  name: deployment-rollouts

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-cron-runner
  labels:
    paas.redhat.com/appcode: SET-002

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
  labels:
    paas.redhat.com/appcode: SET-002