kind: Deployment
apiVersion: apps/v1
metadata:
  name: component-upgrade-logger-jvm
  labels:
    app: component-upgrade-logger
    paas.redhat.com/appcode: SET-001
spec:
  replicas: 0
  selector:
    matchLabels:
      deployment: component-upgrade-logger-jvm
  template:
    metadata:
      labels:
        deployment: component-upgrade-logger-jvm
        paas.redhat.com/appcode: SET-001
    spec:
      containers:
        - name: component-upgrade-logger
          image: images.paas.redhat.com/thofman/component-upgrade-logger:jvm-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: component-upgrades-db-connection
                  key: url
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: component-upgrades-db-connection
                  key: user
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: component-upgrades-db-connection
                  key: password
          resources:
            limits:
              cpu: 100m
              memory: 800Mi
            requests:
              cpu: 50m
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
